#+title: System Configuration

* Bootstrap New Computer

** Step 1 - For MacOS, install Nix package manager

Install the nix package manager, add unstable channel:

#+BEGIN_SRC shell
sh <(curl -L https://nixos.org/nix/install)
#+END_SRC

#+BEGIN_SRC shell
nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
#+END_SRC

#+BEGIN_SRC shell
nix-channel --update
#+END_SRC


** Step 2 - Install home-manager

Add the home-manager channel and install it:

#+BEGIN_SRC shell
nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
nix-channel --update
#+END_SRC


** Step 3 - If MacOS, install Darwin dependencies

Install Xcode CLI tools and nix-darwin:

#+BEGIN_SRC shell
xcode-select --install
#+END_SRC


** Step 4 - Build the environment

Download this repo and run:

#+BEGIN_SRC shell
./bin/build
#+END_SRC


** Step 5 - Reboot computer

That's it. You're done.


* Update Computer

** Update dependencies

#+BEGIN_SRC shell
nix flake update
#+END_SRC


** Run build

#+BEGIN_SRC shell
./bin/build
#+END_SRC


* Manual Stuff

I'm not yet able to configure everything through Nix.
These things need to be manually set to complete all aspects of the system.

** Common

*** Doom Emacs

I prefer Doom to manage Emacs configuration.
Bootstrap Doom through the script ~./bin/doom-bootstrap~.  
It is made available in ~$PATH~ once the configuration been built.


** MacOS

*** GitHub CLI Authentication

Authenticate to ~gh~ (GitHub CLI to enable notifications in /sketchybar/)

#+BEGIN_SRC shell
gh auth login to
#+END_SRC

*** Spicetify

Apply /spicetify/ configuration to theme Spotify client

#+BEGIN_SRC shell
spicetify-cli backup apply
#+END_SRC

*** Raycast

Raycast can not be configured comfortably through Nix currently.
Our custom script directory to start an emacsclient needs to be linked.
Raycast settings > Extensions > Scripts > Script Commands > Add Directories > =~/.local/share/bin=.
